FROM garethflowers/ftp-server

WORKDIR /home/ftp_username/

RUN mkdir -p fromapi1min
RUN chmod 755 fromapi1min

RUN mkdir -p archivefromapi1min
RUN chmod 755 archivefromapi1min

RUN mkdir -p transformedfromapi1min
RUN chmod 755 transformedfromapi1min
